import type { Metadata } from "next";
import { Gilroy } from "@/utils/localFonts";
import Frame from "@/components/views/Frame";

import { ToastContainer } from "react-toastify";

import "./globals.css";
import JotaiProvider from "@/providers/Jotai.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Gilroy.variable}>
        <JotaiProvider>
          <Frame>{children}</Frame>
        </JotaiProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
