import type { Metadata } from "next";
import { Gilroy } from "@/utils/localFonts";
import Frame from "@/components/views/Frame";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Gilroy.variable}>
        <Frame>{children}</Frame>
      </body>
    </html>
  );
}
